### ISSUE TITLE
kpartx no loop0p* in mapper 

### ISSUE THREAD

**Issue by xxxcrow** [ViRb3/pi-encrypted-boot-ssh#1]
No device appears after using the command kpartx also it gives no output and creates loop device that has no partitions in it 
(I hope I could explain it 😅)
Thank you 😃

**Comment by xxxcrow** [comment]
Hi 😃 what should I do? Everything is right or I miss something? 😁

**Comment by ViRb3** [comment]
Hey, I'll need a bit more information to answer that. What distro and version are you using? What exact commands are you running? Is the image you're mouting with `kpartx` corrupt? Does it have partitions?

**Comment by xxxcrow** [comment]
![Screenshot from 2020-08-31 06-48-07](https://user-images.githubusercontent.com/24483751/91672056-0b72a900-eb56-11ea-8ee3-590043ec65b1.png)
host machine is ubuntu 20.4*
`user@user-desktop:~/Downloads$ echo "aadc64a1d069c842e56a4289fe1a6b4b5a0af4efcf95bcce78eb2a80fe5270f4 *ubuntu-20.04.1-preinstalled-server-arm64+raspi.img.xz" | shasum -a 256 --check
ubuntu-20.04.1-preinstalled-server-arm64+raspi.img.xz: OK
`

**Comment by ViRb3** [comment]
Quote from the guide:
```
kpartx -ar "$PWD/ubuntu-20.04-preinstalled-server-arm64+raspi.img"
```

You need to extract your `.img.xz` file to `.img` first.

**Comment by xxxcrow** [comment]
PERFECT!
Thank you for your work, amazing project
I insist to add unpack line into the readme! 
Thank you very much <3

**Comment by ViRb3** [comment]
I appreciate the feedback, but I don't want to make this guide too verbose, and whether the image is packed depends on how you obtained it anyway. I hope that people can find this issue if they have the same problem in the future.
