### ISSUE TITLE
Suggestion: Config as Code

### ISSUE THREAD

**Issue by mihaigalos** [ViRb3/pi-encrypted-boot-ssh#10]
Hi,

Very nice writeup!
Did you consider writing it in code using something like a `Justfile` and recipes?
Check out [just](https://github.com/casey/just) - let me know if I can help in providing an initial structure!

**Comment by ViRb3** [comment]
Hello. Many thanks for the interest in this project. The topic of automation has been raised before as well in #7, and unfortunately, I still believe that it would be a hard thing to maintain for very little purpose. Please read my comment in the linked issue for more information. I hope you understand.
