### ISSUE TITLE
Raspberry pi OS : can you add this step (ssh)

### ISSUE THREAD

**Issue by BlueBlueBlob** [ViRb3/pi-encrypted-boot-ssh#11]
Hi

Best tutorial ever ! You did a very good job ! Seriously.

After a lot of try... I understood why I was not able to connect to my PI after unlocking....
Don't lol please... 

On raspberry pi OS, you need to add the ssh file in the boot partion during chroot part.
Like `touch /boot/ssh`

Great regards 👍

**Comment by ViRb3** [comment]
Done :)
