### ISSUE TITLE
Question about extending target image

### ISSUE THREAD

**Issue by BlueBlueBlob** [ViRb3/pi-encrypted-boot-ssh#12]
Hi 😊

I think we can extend the target image size to make an up-to-date image.
But I'm not sure before or in chroot ?
I will if I have some time.

And thanks again for your work 🙏👍

**Comment by ViRb3** [comment]
You can definitely do it, but then the image file would become huge in size. I would prefer to keep the image small and then adjust the partition as necessary on the device.

**Comment by BlueBlueBlob** [comment]
Is + 500MB huge ?
I understand the point of view. And it's nice to have "usual" img.

Thanks for your reply 🙏

**Comment by ViRb3** [comment]
Well, I personally flash onto 32GB SD cards, so the image would be more like +30GB :)

**Comment by BlueBlueBlob** [comment]
Btw,

I tried to extend target.img with xpart, partx and parted to have more space. It didn't work 😞
Maybe in chroot... But actually it's not useful.

Thank you for your answer.

Great regards
