### ISSUE TITLE
Resize partition on Raspberry pi OS

### ISSUE THREAD

**Issue by BlueBlueBlob** [ViRb3/pi-encrypted-boot-ssh#13]
Hi 😊

Resizing partion was mess because of this line `echo -e "d\n2\nn\np\n2\n\n\nw" | fdisk /dev/mmcblk0`

I did the fdisk part manually, but forget to note step.
Maybe you should explain more.
Like last issue, I will try if time.

Great regards 👍

**Comment by ViRb3** [comment]
That line was more of an example, it will vary depending on your situation. What you need to do is described in the paragraph before, though. I don't want to make the guide too long, and I think that the current text strikes a good balance.

**Comment by BlueBlueBlob** [comment]
Hi

Thanks for your answer. I understand.

If people reading this issue want some information :
https://blog.tinned-software.net/increase-the-size-of-a-luks-encrypted-partition/

I can remove the link if you dislike.

And thank you again for your job 👍🙏

**Comment by ViRb3** [comment]
Raspberry Pi OS is now officially supported, check updated docs.

**Comment by BlueBlueBlob** [comment]
Thank you, I can remove my fork.
You did a very good job 🤩
Thank you again 🙏🙏🥰
