### ISSUE TITLE
Improve : add steps after a kernel update (raspiOs)

### ISSUE THREAD

**Issue by BlueBlueBlob** [ViRb3/pi-encrypted-boot-ssh#14]
Dear,

Can you add instructions for a kernel update please ?

Easy : it's already in your how-to. In the part to make the initdr.img
So steps will be like :
1. `sudo apt udpate && sudo apt udgrade`
2. Check if you have a kernel update. And accept updates.
3. DON'T REBOOT !
4. `ls /lib/modules/` and check your latest kernel version.
5. `mkinitramfs -o /boot/initrd.img "[see step4]"`
6. Now you can reboot.

(raspiOs x64)

Cheers

**Comment by ViRb3** [comment]
Hey there,

At least on Ubuntu, initramfs will be automatically re-generated every time there is a kernel update. So all you need to do is `apt upgrade`. To keep things simple I won't add instructions for other distros in the guide, but people with your problem can hopefully find this issue.

**Comment by BlueBlueBlob** [comment]
Dear,

You already added instructions for raspberry pi OS.
At least you should warn the initfmrs will not be rebuild automatically. And after a kernel update unlocking root partition will fail.

Great regards and sorry

**Comment by ViRb3** [comment]
I have only mentioned Ubuntu as a tested distribution. As similar as the steps may be for your distro, I don't want to go down the road of listing all exceptions and making the guide both harder to maintain and more confusing. I hope you understand. Also, I don't think that manually running `mkinitramfs` after each update is the way to go. There should definitely be a way for you to set up automatic initramfs re-generation on your distro.

**Comment by BlueBlueBlob** [comment]
Hi,

I understand. I have forked your repo for raspberry pi OS. So I will not disturb you anyway.

Great regards and good job

**Comment by ViRb3** [comment]
An update for future readers. Raspberry Pi OS indeed does not use initramfs, so it will not get used or re-generated on update by default. You need to change a few things to make it work, check here:
- https://raspberrypi.stackexchange.com/questions/92557/how-can-i-use-an-init-ramdisk-initramfs-on-boot-up-raspberry-pi/

**Comment by ViRb3** [comment]
Raspberry Pi OS is now officially supported, check updated docs.
