### ISSUE TITLE
[HELP] image is not booting

### ISSUE THREAD

**Issue by 555richardb** [ViRb3/pi-encrypted-boot-ssh#16]
Hi there,
I like the guide (kudos to you) and it makes perfect sense but is is possible to tshoot this somehow because my image is not booting. (or not obtaining IP)
My setup is a ```2022-04-04-raspios-bullseye-arm64-lite.img``` pi3 or 4 iamge and a vanilla amd64 debian install.
The process went fine. There was only one minor issue namely in the ssh_key section (possibly in debian) it is not ```/etc/dropbear/initramfs/``` but ```/etc/dropbear-initramfs/```.(but I don't think it would cause the image not to boot)
Booting the image gives only a blinking cursor. checked with wireshark and not even requesting for IP through DHCP.

Richard

**Comment by ViRb3** [comment]
Hey there,

I'm afraid that this guide is only tested and supported on Ubuntu, and I don't have the resources to change this any time soon. Anyway, you should be able to extract logs during boot and see what's wrong, but I have never used Raspbian so I'm not sure what's the best way to do that. Maybe reach out to @BlueBlueBlob, I remember they were experimenting with Raspbian before.

**Comment by BlueBlueBlob** [comment]
Thank you 🙏
My fork is still working 🙏 Because of you 🙏
Great regards 🙏

**Comment by 555richardb** [comment]
Thank you. I'll try that out.

**Comment by ViRb3** [comment]
Raspberry Pi OS is now officially supported, check updated docs.
