### ISSUE TITLE
SSH KEYS - echo "/REDACTED/"

### ISSUE THREAD

**Issue by xxxcrow** [ViRb3/pi-encrypted-boot-ssh#2]
`root@user-desktop:/# echo "/REDACTED/" > /etc/dropbear-initramfs/authorized_keys`

and then after `mkinitramfs -o /boot/initrd.img "5.4.0-1015-raspi"`
 
`dropbear: WARNING: Invalid authorized_keys file, remote unlocking of cryptroot via SSH won't work!`

need help with the keys, how to make, where to move 
thank you :D

**Comment by ViRb3** [comment]
You need to echo your __public key__ in there, the REDACTED text is just a placeholder.

Here's a SSH guide that I found online:
https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server

I recommend that you learn how SSH works in detail before proceeding with this guide, as it is crucial to maintaining proper security.

**Comment by xxxcrow** [comment]
> You need to echo your __public key__ in there, the REDACTED text is just a placeholder.
> 
> Here's a SSH guide that I found online:
> https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server
> 
> I recommend that you learn how SSH works in detail before proceeding with this guide, as it is crucial for maintaining proper security.

I know how ssh works, but chroot for me is too confusing, I get lost in basic tasks (I don't know chroot 😅)
(And also I didn't use keys for some years, and a lot of new versions appeared, and sometimes I get errors because I do it in the old way(that's why I ask, to make everything correctly))
