### ISSUE TITLE
Wrong initramfs generated for Pi 5 kernel

### ISSUE THREAD

**Issue by LouisMT** [ViRb3/pi-encrypted-boot-ssh#21]
When building initramfs for the Pi 5 kernel (6.1.0-rpi7-rpi-2712), the guide builds `initramfs8` instead of `initramfs_2712`.

Just to illustrate, the script below would fix this. I think a simple comment might be more suitable, but I wasn't sure about the phrasing (especially because of the subtle differences between `v8/8` and `2712`/`_2712`).

```bash
# RPi5 with 16K pages = 2712, RPI5 or all others with 4K pages = v8
kversion="6.1.0-rpi7-rpi-v8"

case "$kversion" in
  *v8)
    iversion="initramfs8";;
  *)
    iversion="initramfs_2712";;
esac

echo "CONFIG_RD_ZSTD=y" > /boot/config-$kversion
mkinitramfs -o /boot/$iversion $kversion
rm /boot/config-$kversion
```

**Comment by ViRb3** [comment]
I thought it makes sense with the existing comment that you need to change the suffix of both the kernel and initramfs? Do you not think that's the case?

**Comment by LouisMT** [comment]
The comment does certainly make sense! But I completely overlooked the name of initramfs, because I saw the variable being used on every line so I assumed I only had to change the variable. Also, the suffix for initramfs is slightly different from the kernel's suffix.

**Comment by ViRb3** [comment]
I reworded to make it more clear, thanks!
