### ISSUE TITLE
Couldn't resolve device /dev/mmcblk0p2

### ISSUE THREAD

**Issue by xxxcrow** [ViRb3/pi-encrypted-boot-ssh#3]
`root@user-desktop:/# mkinitramfs -o /boot/initrd.img "5.4.0-1015-r"spi"`
`cryptsetup: ERROR: Couldn't resolve device /dev/mmcblk0p2`
`cryptsetup: WARNING: target 'sda6_crypt' not found in /etc/crypttab`

is it ok? ':)

**Comment by ViRb3** [comment]
The first error is okay because mmcblk0p2 will only exist on the Pi, it uses a different name on your computer. The second I'm not sure about.
