### ISSUE TITLE
Warning about using partition UUIDs

### ISSUE THREAD

**Issue by tvdstaaij** [ViRb3/pi-encrypted-boot-ssh#4]
First of all, very useful guide, thank you!

The "Device configuration" section has a warning

> NOTE: Since the device name will likely be different on the Raspberry Pi, make sure to use the name that will be found on the Pi. Do not use UUIDs since cryptsetup will try to play smart and resolve them to a device name at build time.

This is a problem for me; I use the USB boot feature recently added to the Raspberry Pi firmware, and since USB mass storage devices are not exactly known to be deterministic in Linux, it is widely recommended to use UUID or PARTUUID rather than device paths.

Because I found it a bit weird that this would be a problem and couldn't find other information indicating this behavior, I just tried it with a PARTUUID and it seems to work perfectly fine.  I can't find any reference to the host device name in the extracted initramfs either. So I'm wondering what this warning is based on exactly, is this maybe only a problem under certain circumstances? Or perhaps confused with a different problem?

For reference, I tested with an Ubuntu 20.10 image. (I picked that over LTS because the LTS has some complications with USB boot)

**Comment by keks24** [comment]
> it is widely recommended to use UUID or PARTUUID rather than device paths.

Indeed it is.

I think, he had issues with the wrong `UUID`. There are two, if the `LUKS partition` is decrypted:
```bash
$ blkid
/dev/sda1: UUID="fae82537[...]" TYPE="crypto_LUKS" PARTLABEL="root" PARTUUID="db9b80[...]
/dev/mapper/cryptroot: UUID="79116078[...] BLOCK_SIZE="4096" TYPE="ext4"
```

If you want to use the `UUID`, take the one with the type `crypto_LUKS`. The other one is invisible to the systen until it is decrypted.

**Comment by ViRb3** [comment]
Thanks a lot for the responses to both of you! I've been planning to test these changes and update the guide for a long time, but I still don't have access to a Raspberry Pi. Will hopefully make the changes soon.

**Comment by keks24** [comment]
Sure thing! Maybe you want to be inspired by my results as well? :)

https://github.com/keks24/raspberry-pi-luks

**Comment by ViRb3** [comment]
I just created a new image using the UUID in `crypttab` instead of the hardcoded path:
```sh
crypted  UUID=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa  none  luks,initramfs
```

I flashed the image, and the initramfs boots. However, running `cryptroot-unlock` hangs and does nothing. Upon investigation, my fears are confirmed:
```
$ cat /cryptroot/crypttab
crypted /dev/mapper/loop1p2 none luks,initramfs
```

The UUID was resolved to a hardcoded path at build time. That path was valid on the host computer, but is not valid on the Raspberry Pi. This causes decryption to fail. Any thoughts?

**Comment by ViRb3** [comment]
If I use a PARTUUID then I get the following error when making the initramfs:
```
cryptsetup: ERROR: crypted: Source mismatch
```
However, the PARTUUID does not get resolved at build time and works as expected on runtime.

**Comment by ViRb3** [comment]
After inspecting the default `initramfs-tools` hooks I can confirm that `crypttab` UUIDs are resolved to a device name _at build time_, at least on Ubuntu Server 21.04. PARTUUIDs seem to be unsupported, thus generating the error I mentioned above and bypassing this resolution step, which so happens to produce a working `crypttab` for the Raspberry Pi.

The code responsible for this step can be found under:
```
/usr/share/initramfs-tools/hooks/cryptroot
```
[cryptroot.txt](https://github.com/ViRb3/pi-encrypted-boot-ssh/files/6448820/cryptroot.txt)

Notice `crypttab_find_and_print_entry`  - it calls `crypttab_print_entry` which in turn tries to resolve the device name via `_resolve_device`. At the end of `crypttab_print_entry` the resolved `crypttab` line is printed:
```sh
    printf '%s %s %s %s\n' \
        "$_CRYPTTAB_NAME" "$_CRYPTTAB_SOURCE" "$_CRYPTTAB_KEY" "$_CRYPTTAB_OPTIONS" >&3
```
My current solution is to patch the hook script and prevent the resolution. Please let me know if you have any better ideas.

**Comment by keks24** [comment]
> @tvdstaaij @keks24 I just created a new image using the UUID in `crypttab` instead of the hardcoded path:
> 
> ```shell
> crypted  UUID=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa  none  luks,initramfs
> ```
> 
> I flashed the image, and the initramfs boots. However, running `cryptroot-unlock` hangs and does nothing. Upon investigation, my fears are confirmed:
> 
> ```
> $ cat /cryptroot/crypttab
> crypted /dev/mapper/loop1p2 none luks,initramfs
> ```
> 
> The UUID was resolved to a hardcoded path at build time. That path was valid on the host computer, but is not valid on the Raspberry Pi. This causes decryption to fail. Any thoughts?

Interesting! This seems to be a "Ubuntu-thing" then.

On a `Raspberry Pi OS Lite image` it does get resolved properly:

https://github.com/keks24/raspberry-pi-luks/issues/1#issuecomment-826114833

**Comment by ViRb3** [comment]
@keks24 just tested this on Raspberry Pi OS Lite, Debian 11, kernel 5.15, 64-bit, and it follows the exact same behavior as Ubuntu. Therefore, my patch is now necessary there too.

**Comment by keks24** [comment]
@ViRb3, thanks for the heads-up!
