### ISSUE TITLE
Purpose of qemu

### ISSUE THREAD

**Issue by tvdstaaij** [ViRb3/pi-encrypted-boot-ssh#5]
I was wondering about the purpose of the qemu installation and `cp` of the qemu binary into the chroot. I don't see qemu being used anywhere in the process, and I get a working result without installing qemu at all. Is this a leftover from an old version that did require qemu, or am I overlooking something?

**Comment by keks24** [comment]
@tvdstaaij 

You need `qemu-<cpu_architecture>-static`, if you are working on a system with a different CPU architecture.

**Comment by ViRb3** [comment]
I can confirm what @keks24 said. Since most people work on a x86-64 host and the Pi's image is arm64, whenever you attempt to enter the chroot without qemu installed you will get the following error:
```
chroot: failed to run command '/bin/bash': Exec format error
```

**Comment by ViRb3** [comment]
However, it seems like copying the binaries inside the chroot is unnecessary - simply installing the package is enough. I will reflect this in the new update I am finishing today.
