### ISSUE TITLE
initramfs-tools cryptroot patch original gets executed on mkinitramfs

### ISSUE THREAD

**Issue by happy-sadan** [ViRb3/pi-encrypted-boot-ssh#6]
Applying the recommended patch to `/usr/share/initramfs-tools/hooks/cryptroot` creates a `cryptroot.orig` file in the same directory, which gets executed when running `mkinitramfs`, and returns the following:

```
(...)
Calling hook cryptroot-unlock
Adding script /usr/share/cryptsetup/initramfs/bin/cryptroot-unlock
Calling hook cryptroot.orig
/usr/bin/mkdir: cannot create directory '/var/tmp/mkinitramfs_xxxxxx/cryptroot': File exists
Copying module directory kernel/arch/arm/crypto
Copying module directory kernel/crypto
E: /usr/share/initramfs-tools/hooks/cryptroot.orig failed with return 1.
```

Removing the file or, better yet, running `chmod -x /usr/share/initramfs-tools/hooks/cryptroot.orig`, fixes the issue.

**Comment by ViRb3** [comment]
Hello. Many thanks for the report, I didn't realize that the patch makes a backup. I'll update the guide in a few minutes. What distro and version are you trying to encrypt? I don't get the same error on Ubuntu 21.04.

**Comment by ViRb3** [comment]
@happy-sadan I just tested again and Ubuntu 21.04 definitely does not create a backup file. What distro is it that you're trying to encrypt? Can you please try the following command and see if it prevents the backup from being created?

Instead of:
```
patch /usr/share/initramfs-tools/hooks/cryptroot ...
```
Run:
```
patch --version-control=none /usr/share/initramfs-tools/hooks/cryptroot ...
```

Many thanks

**Comment by happy-sadan** [comment]
I'm installing *Raspberry Pi OS Lite*, I got confused about the "Raspberry Pi OS image" requirement, thinking it referred to the eponymous distro. This might be worth clarification though (I thought it being called Ubuntu was a remnant of the past or something).

In my case, running `patch --version-control=none` creates a `cryptroot.~1~` backup, numbered accordingly.

**Comment by ViRb3** [comment]
Thank you for checking. I tested your steps for myself on Raspbian and the problem ended up being that `patch` will create a backup if the diff's line numbers do not exactly match, even if the diff successfully fuzzy matches. I simply added the flag `--no-backup-if-mismatch` to prevent this from happening. I also reworded all the "Raspberry Pi OS image" terms, I agree that they were a bit confusing. Please let me know if there's anything else that can be improved with this guide.
