### ISSUE TITLE
feat: Wireguard Tunnel

### ISSUE THREAD

**Issue by al13nus** [ViRb3/pi-encrypted-boot-ssh#8]
Hey, 

thank you for this guide. Is it possible for you to add an howto wireguard connection? Its nice and easy at the end to connect to local rpi, but what if its somewhere outside in the world without knowing its real address?

**Comment by ViRb3** [comment]
> Hey,
> 
> thank you for this guide. Is it possible for you to add an howto wireguard connection? Its nice and easy at the end to connect to local rpi, but what if its somewhere outside in the world without knowing its real address?

This is not something that I've tried or know how to do I'm afraid. if you get it to work, feel free to open a PR with some documentation.

> also having this error all the time. Tried like 3-4 times the full install guide:
> 
> ```
> BusyBox v1.30.1 (Ubuntu 1:1.30.1-4ubuntu6.3) built-in shell (ash)
> Enter 'help' for a list of built-in commands.
> 
> # cryptroot-unlock
> Error: Timeout reached while waiting for askpass.
> ```

Did you enter your password followed by enter after typing `cryptroot-unlock`? It seems like it was waiting for the password for too long and timed out.

**Comment by al13nus** [comment]
> Did you enter your password followed by enter after typing `cryptroot-unlock`? It seems like it was waiting for the password for too long and timed out.

If I startup the RPi and connect via SSH to it, its first asks me "login as:". I write root. Then it logins automaticly and I'm in the busy box. I write "cryptroot-unlock" and nothing really happens. It just loads and then there is this error. What should I have seen after entering the cryptroot-unlock command?

**Comment by al13nus** [comment]
Maybe this will help you. My steps:

1. Downloaded `ubuntu-20.04.3-preinstalled-server-arm64+raspi.img`
2. moved this to $PWD as ubuntu-base.img and ubuntu-target.img (like in your doc)
3. did all the steps from your guide. Changed only the pbkdf-memory to `1024000`, because RPI4 with 8GB
4. Tried also both approaches at Cryptsetup setp with this overwritting
5. After all the steps moved the target.img to Windows and "burned" to microSD-Card
6. Started RPI and connected with Privat Key to it
7. Entered `root` for `login as:` and then `cryptroot-unlock` in BusyBox
8. Its loading something and then promts the error

**Comment by al13nus** [comment]
I tried now with 21.10 and it worked!
